### ISSUE TITLE
能不能tag一下跟hbx对应的版本

### ISSUE THREAD

**Issue by Mrokor** [dcloudio/uni-preset-vue#10]
能不能tag一下跟hbx对应的版本，不然npm update 一升级就没有合适版本的基座调试了

**Comment by fxy060608** [comment]
版本号说明：
npm update之后，@dcloudio相关的包版本号类似：`2.0.0-26520200314001`
其中`26520200314`对应着HBuilderX的版本`2.6.5.20200314`

**Comment by zhetengbiji** [comment]
https://www.npmjs.com/package/@dcloudio/uvm
