### ISSUE TITLE
@vue/cli-plugin-babel 版本升级

### ISSUE THREAD

**Issue by Ttou** [dcloudio/uni-preset-vue#12]
现在模板里 `@vue/cli-plugin-babel` 的版本是 3.5.1，如果升级到 4.1.2 启动项目就会报错，该怎么改？
![1578554556](https://user-images.githubusercontent.com/4298437/72046905-4e94b900-32f4-11ea-9443-99dfbcec35e0.png)

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/1394
