### ISSUE TITLE
vue create -p dcloudio/uni-preset-vue 能否创建对应HBuilder 版本的资源

### ISSUE THREAD

**Issue by zhuSass** [dcloudio/uni-preset-vue#16]
需求来源：老项目是通过HBuilder 创建的，现在想改成vue-cli方式来管理项目，但是通过`vue create -p dcloudio/uni-preset-vue`创建默认是下载最新版本，所依赖的包都是最新(v2.8)的版本的包，我想通过改package.json版本进行修改，但是之前通过HBuilder创建的项目没有package.json文件，请教这个该怎么处理
解决思路：
1、提供HBuilder 版本对应的资源包版本
2、dcloudio/uni-preset-vue提供一个参数可以选择对应HBuilder 版本进行创建项目

**Comment by zhetengbiji** [comment]
https://www.npmjs.com/package/@dcloudio/uvm
