### ISSUE TITLE
TS模板 h5端无法加载sourcemap

### ISSUE THREAD

**Issue by yanxiaoleng** [dcloudio/uni-preset-vue#18]
DevTools 无法加载 SourceMap： 无法加载 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by yanxiaoleng** [comment]
![Uploading QQ截图20200924161013.png…]()

**Comment by yanxiaoleng** [comment]
问题重新步骤
第一步
```vue create -p dcloudio/uni-preset-vue my-project```
第二步选择typescript模板
第三步yarn serve

然后控制台就可以看到 输入对齐的文件映射都是null

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/2120
