### ISSUE TITLE
初始化 vue3 ts 模板无法正常启动

### ISSUE THREAD

**Issue by richard1015** [dcloudio/uni-preset-vue#27]
```
vue create -p dcloudio/uni-preset-vue#vue3 uniapp-vue3


npm run serve 报错
```

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/131825632-6cd905c2-75cc-43ba-b3ad-3b9147a97681.png)

**Comment by richard1015** [comment]
复现仓库 https://github.com/jdf2e/nutui-demo/tree/master/uniapp-vue3

**Comment by richard1015** [comment]
可以看一下吗  @zhetengbiji

**Comment by dwfrost** [comment]
https://ask.dcloud.net.cn/article/id-37834__page-2注意：此模式创建的项目，仅支持编译到小程序，不支持编译到H5/App 平台。

**Comment by dwfrost** [comment]
https://ask.dcloud.net.cn/article/id-37834__page-2
注意：此模式创建的项目，仅支持编译到小程序，不支持编译到H5/App 平台。

**Comment by zhetengbiji** [comment]
参考：https://ask.dcloud.net.cn/article/37834，改用如下方式：

```
npx degit dcloudio/uni-preset-vue#vite my-vue3-project
```
