### ISSUE TITLE
部分类型声明不正确

### ISSUE THREAD

**Issue by 1018715564** [dcloudio/uni-preset-vue#29]
![image](https://user-images.githubusercontent.com/35763284/133094287-b71e2892-db3c-4475-915f-98c06cf76336.png)

string就别定义2遍了，where是可以传递Record<string, unknown>

cloud.d.ts

另外亚琪哥你们这个类型怎么自定义啊，虽然是工具生成的type，而且不能提交pr，我们开发者只能自己定义了。

我自己定义其他一些模块还可以，这个type模块真的把我搞懵了，层级太多了。我微信就不找你了，现在时间太晚了。

**Comment by Wangyaqi** [comment]
感谢反馈，重复类型的问题我们修改一下。Record目前不好处理，暂时返回any
