### ISSUE TITLE
拉取vite-ts版本后，无法在微信小程序内运行

### ISSUE THREAD

**Issue by taixingyiji** [dcloudio/uni-preset-vue#33]
![image](https://user-images.githubusercontent.com/51304768/145777566-ee784dba-ca9c-4ba1-9e2d-296ad092c2d9.png)

**Comment by fxy060608** [comment]
已修复，可以升级相关依赖为：3.0.0-alpha-3030120211213002
或者重新创建项目

**Comment by taixingyiji** [comment]
> 已修复，可以升级相关依赖为：3.0.0-alpha-3030120211213002 或者重新创建项目

测试可以了！谢谢！
