### ISSUE TITLE
关于分包的问题，使用分支为vite-ts

### ISSUE THREAD

**Issue by taixingyiji** [dcloudio/uni-preset-vue#34]
使用vite-ts分支。

项目包含两个分包main和wasm。

main为主包。

wasm为子包。

通过yarn add引入一个很大的依赖，然后将此依赖封装成一个.ts工具放入wasm的lib文件夹下，且此工具类**只在**wasm包中引用过

![image](https://user-images.githubusercontent.com/51304768/145788242-c31e1363-1b8c-4a6b-856b-93bdf88b2dca.png)

manifest.json也配置了

`"optimization" : {
            "subPackages" : true
        }`

但是执行 `yarn dev:mp-weixin` 后，结果如下，vendor.js文件并没有分包。

![image](https://user-images.githubusercontent.com/51304768/145788153-9c5281d6-87ac-4663-b05a-5a4df12832c2.png)
![image](https://user-images.githubusercontent.com/51304768/145788209-a7b520d2-b10b-4891-a57d-b4d7c848fe78.png)

**Comment by fxy060608** [comment]
该特性目前暂未支持（目前可以手动将该依赖放入分包目录里引用），uni-app问题，建议在 https://github.com/dcloudio/uni-app/issues 中反馈

**Comment by taixingyiji** [comment]
> 该特性目前暂未支持（目前可以手动将该依赖放入分包目录里引用），uni-app问题，建议在 https://github.com/dcloudio/uni-app/issues 中反馈

好的，谢谢
