### ISSUE TITLE
设置环境变量

### ISSUE THREAD

**Issue by jzYuchn** [dcloudio/uni-preset-vue#35]
请问一下，uni-app 通过vue-cli创建的vue3.0项目怎么设置环境变量呢？
之前在运行或者打包脚本添加cross-env NODE_ENV=test UNI_PLATFORM=mp-weixin vue-cli-service uni-build就可以传入环境变量，现在咋都不行，cross-env NODE_ENV=test VUE_APP_ENV=test uni build -p mp-weixin这样不行，用vue3的那种方式添加.env.test文件也不行

**Comment by fxy060608** [comment]
vue-cli创建的webpack工程不再维护，
请更换为vite版本，`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
环境变量：
https://cn.vitejs.dev/guide/env-and-mode.html

**Comment by jzYuchn** [comment]
> 

感谢大佬，看了下这个文档https://cn.vitejs.dev/guide/env-and-mode.html，原来是我使用变量的写法问题
