### ISSUE TITLE
app里面的组件都是英文版的

### ISSUE THREAD

**Issue by parahell1** [dcloudio/uni-preset-vue#36]
用hbuilder创建的项目没问题，但是用cli创建的项目里面的比如picker组件显示的是cancel done英文版的
h5端没问题，app端显示英文版的
![QQ截图20211225111732](https://user-images.githubusercontent.com/57480451/147376621-4efd39f3-04dc-4b3f-a5f5-ec6c6caa528c.jpg)

**Comment by zhetengbiji** [comment]
新版已修复
