### ISSUE TITLE
使用 vue create -p dcloudio/uni-preset-vue proj 长时间没有完成

### ISSUE THREAD

**Issue by zwq000** [dcloudio/uni-preset-vue#4]
通过命令 vue create -p dcloudio/uni-preset-vue 创建项目时长时间没有完成.
猜测 是git 存储库中包含 node_modules, 导致下载时间过长.
不过也没有看到错误信息或日志,无法查明原因.

**Comment by fxy060608** [comment]
可以手动下载 uni-preset-vue,然后 create 时，指定本地下载的 preset 目录
