### ISSUE TITLE
vue create -p dcloudio/uni-preset-vue xxx后报错 ERROR  TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-preset-vue#41]
vue create -p dcloudio/uni-preset-vue xxx
安装了官方推荐的webpack4之后
npm run dev:h5
就会报错ERROR TypeError: Cannot convert undefined or null to object

**Comment by altriayu** [comment]
同样的问题，正在想办法看怎么解决

**Comment by zhetengbiji** [comment]
具体描述一下
