### ISSUE TITLE
vite 版本 resolve alias 失效

### ISSUE THREAD

**Issue by myjustify** [dcloudio/uni-preset-vue#42]
vite 版本 resolve alias 失效
在vite.config 配置了 
```  javascript
resolve: {
  alias: {
    '@': path.resolve(__dirname, 'src')
  }
}
```

用@引用模块是就报错
[plugin:vite:load-fallback] Could not load

**Comment by fxy060608** [comment]
已内置支持@别名，无需自己手动配置，如果还有问题，发测试工程

**Comment by myjustify** [comment]
> 已内置支持@别名，无需自己手动配置，如果还有问题，发测试工程

👌 升级完引入没有问题了 谢谢
