### ISSUE TITLE
vite分支的代码，在编译成微信小程序后，小程序AppData调试下展示的数据都是（a、b...）

### ISSUE THREAD

**Issue by ityadong** [dcloudio/uni-preset-vue#47]
```
<script setup>
import { ref } from 'vue'
let title = ref('Hello World')
let color = ref('blue')
</script>
```

![image](https://user-images.githubusercontent.com/33867329/157393867-1a119161-c521-4c48-ae56-e07cc04f5897.png)

**Comment by fxy060608** [comment]
小程序平台会对数据传输做优化，不支持看到原始数据，后续会提供vue devtools

**Comment by Megasu** [comment]
新年好，关注该问题。🌹

**Comment by ityadong** [comment]
uni-vue-devtools 调试
https://uniapp.dcloud.net.cn/tutorial/debug/uni-vue-devtools.html#uni-vue-devtools
