### ISSUE TITLE
vite-ts分支，编译到微信小程序平台后，微信开发者工具模拟器里appData数据是混淆的

### ISSUE THREAD

**Issue by moslixiansen** [dcloudio/uni-preset-vue#49]
- 分支： vite-ts
- 平台： 微信小程序
- 问题： 微信开发者工具-调试器-AppData 数据不对，如下图。

![image](https://user-images.githubusercontent.com/31963147/165919392-3ca750d8-2542-4eed-8721-f336b2feeb53.png)

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3192
