### ISSUE TITLE
选择 Hello uni-app 模板生成项目失败

### ISSUE THREAD

**Issue by auven** [dcloudio/uni-preset-vue#5]
运行
``` bash
vue create -p dcloudio/uni-preset-vue my-project
```

报错信息：` ERROR  TypeError: Cannot read property 'projectName' of undefined` ，如下图
![image](https://user-images.githubusercontent.com/23731087/53149493-ce386d00-35e8-11e9-8654-adb3e823f15e.png)

**Comment by auven** [comment]
已解决 https://github.com/dcloudio/uni-preset-vue/commit/5e3a96118200de1c220c89ff223ae05433460619

**Comment by fxy060608** [comment]
你的 vue cli3 版本号是多少？是不是比较低？

**Comment by auven** [comment]
vue cli3 版本是 `3.4.0` ，已经是最新的了。你上面那个修改已经解决了这个问题了

**Comment by fxy060608** [comment]
上边的修改只是加了容错，理论上是不应该出来 rootOptions 为空的啊。
