### ISSUE TITLE
 Cannot find module webpack

### ISSUE THREAD

**Issue by damengshu** [dcloudio/uni-preset-vue#50]
![image](https://user-images.githubusercontent.com/65537962/167251085-48458101-fa67-43a4-bb65-f318da2a9fbe.png)

node v12.22.12 
@vue/cli 5.0.4

**Comment by damengshu** [comment]
@vue/cli 4.5.15  ok

**Comment by zhetengbiji** [comment]
目前仅支持 4，未支持 5

**Comment by wujinhong** [comment]
测试版和正式版出很久了。为什么还不支持5.0?
5.0.0-alpha.0 (2020-12-14)
5.0.0 (2022-02-17)

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3723
