### ISSUE TITLE
Error: Cannot find module 'webpack/lib/RuleSet'

### ISSUE THREAD

**Issue by wujinhong** [dcloudio/uni-preset-vue#52]
测试版和正式版出很久了。为什么还不支持5.0?
5.0.0-alpha.0 (2020-12-14)
5.0.0 (2022-02-17)
![image](https://user-images.githubusercontent.com/4360345/174590243-5594ad9a-41ad-4db7-8332-62f333d0eb23.png)

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3723
