### ISSUE TITLE
HBuilderX mac M1编译 vite/vue3 cli项目时编译不了

### ISSUE THREAD

**Issue by ZhengKe996** [dcloudio/uni-preset-vue#53]
<img width="1080" alt="Snipaste_2022-07-10_14-47-30" src="https://user-images.githubusercontent.com/82481893/178134466-0098fb9a-0cd6-4145-907b-6b1bcccfd2dc.png">

解决方法: 此方法不受版本限制，请官方及时修改

重新安装依赖 将 node_modules/esbuild-darwin-arm64 修改为 esbuild-darwin-64
<img width="1094" alt="Snipaste_2022-07-10_14-43-13" src="https://user-images.githubusercontent.com/82481893/178134452-d5360d6c-7dd0-42f5-bd06-42cb06163b27.png">

<img width="1014" alt="Snipaste_2022-07-10_14-46-48" src="https://user-images.githubusercontent.com/82481893/178134459-d9198e80-dd8d-4add-893d-b1504cdf830f.png">

**Comment by fxy060608** [comment]
当使用HBuilderX运行时，使用的是HBuilderX自带的node，npm，导致环境识别错误，加载了错误的npm包，后续HBuilderX会修复此问题，临时自己可以修改包名
