### ISSUE TITLE
Error: Cannot find module '@dcloudio\uni-app-plus\lib\uni.plugin.js'

### ISSUE THREAD

**Issue by 48021129** [dcloudio/uni-preset-vue#54]
2.0.1-alpha-35120220706001

**Comment by zhetengbiji** [comment]
详细描述一下

**Comment by 48021129** [comment]
> 

https://github.com/dcloudio/uni-preset-vue/tree/vite-alpha
这个分支，你拉下来跑一下就知道了。

**Comment by zhetengbiji** [comment]
> > 
> 
> https://github.com/dcloudio/uni-preset-vue/tree/vite-alpha 这个分支，你拉下来跑一下就知道了。

感谢提醒，依赖版本以修正为：3.0.0-alpha-3050120220706001

**Comment by 48021129** [comment]
不客气
