### ISSUE TITLE
cli下载的模版依赖

### ISSUE THREAD

**Issue by ctocode** [dcloudio/uni-preset-vue#69]
cli下载的hello 等项目模版，使用的是 @^2.0.1-alpha- 的依赖。能否同步升级一下？用正式的依赖吗？
正式的和 alpha 作为项目上线是否有什么区别？

**Comment by ctocode** [comment]
"dependencies": {
    "@dcloudio/uni-app": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-app-plus": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-h5": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-i18n": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-360": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-alipay": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-baidu": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-jd": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-kuaishou": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-lark": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-qq": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-toutiao": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-vue": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-weixin": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-xhs": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-quickapp-native": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-quickapp-webview": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-stacktracey": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-stat": "^2.0.1-alpha-36920221121001",
    "@vue/shared": "^3.0.0",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.0.4",
    "@dcloudio/uni-automator": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-cli-i18n": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-cli-shared": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-migration": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-template-compiler": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.1-alpha-36920221121001",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.1-alpha-36920221121001",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.1-alpha-36920221121001",
    "@vue/cli-plugin-babel": "~4.5.19",
    "@vue/cli-service": "~4.5.19",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "sass": "^1.49.8",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by zhetengbiji** [comment]
看下这部分文档是否对你有帮助：https://uniapp.dcloud.net.cn/quickstart-cli.html

**Comment by ctocode** [comment]
就是看了这个手册。目前电脑版本@vue/cli 4.5.19，下载下来的不管默认，还是hello模版都是 使用alpha


> 看下这部分文档是否对你有帮助：https://uniapp.dcloud.net.cn/quickstart-cli.html

**Comment by zhetengbiji** [comment]
已更新模板。

可以重新下载模版，也可以使用版本管理工具升级依赖。
