### ISSUE TITLE
突然来个悄无声息的 Break Change ?

### ISSUE THREAD

**Issue by LiangWei88** [dcloudio/uni-preset-vue#76]
之前的代码在现在新的模板里面运行不了, 就因为你多加了个 uni.promisify.adaptor
本来原本的数组式返回, 就难受, 也还行, 就用呗, 突然你来搞一个变化, 没啦!
文档有哪里提示么? 看得我一脸懵逼

**Comment by zhetengbiji** [comment]
这个是加在新模版里，不会自动更新到你的项目里。
