### ISSUE TITLE
使用vue3/vite版，如何在编译时指定特殊环境，例如想让process.env.NODE_ENV=test

### ISSUE THREAD

**Issue by seepine** [dcloudio/uni-preset-vue#83]
尝试使用cross-env配置但无效，是因为`uni build`命令默认为prod了吗
```node
cross-env NODE_ENV=test UNI_OUTPUT_DIR=dist/build/mp-weixin-test uni build -p mp-weixin
```

**Comment by 476421978** [comment]
同问

**Comment by 476421978** [comment]
> 尝试使用cross-env配置但无效，是因为`uni build`命令默认为prod了吗
> 
> ```js
> cross-env NODE_ENV=test UNI_OUTPUT_DIR=dist/build/mp-weixin-test uni build -p mp-weixin
> ```

看这里不知道是不是你想要的

**Comment by 476421978** [comment]
> 尝试使用cross-env配置但无效，是因为`uni build`命令默认为prod了吗
> 
> ```js
> cross-env NODE_ENV=test UNI_OUTPUT_DIR=dist/build/mp-weixin-test uni build -p mp-weixin
> ```

看这里改用vite配置文件：https://github.com/dcloudio/uni-preset-vue/issues/35#issuecomment-994258623
