### ISSUE TITLE
cli 按照包的时候提示警告

### ISSUE THREAD

**Issue by github-ZH-cn** [dcloudio/uni-preset-vue#97]
![image](https://github.com/dcloudio/uni-preset-vue/assets/67533362/b9b92d20-0f08-4575-93c2-06ae32cd2a0b)
这个如何解决

**Comment by Otto-J** [comment]
感谢反馈。实际运行没啥影响。

因为大家用的都是定制过的vue，目前我们的vue版本是3.4.21，安装官方的 vue 实际上更多是用来类型提示
